language: php

sudo: required

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
      env: CODE_COVERAGE=1

addons:
  hosts:
    - dovecot.travis.dev

env:
  global:
    - IMAP_SERVER_NAME=dovecot.travis.dev
    - IMAP_SERVER_PORT=993
    - IMAP_USERNAME=dovecot_travis_testuser
    - IMAP_PASSWORD=dovecot_travis_testpwd

cache:
  directories:
    - $HOME/.composer/cache

install:
  - sh .travis/dovecot_install.sh
  - if [ "$CODE_COVERAGE" != 1 ]; then phpenv config-rm xdebug.ini || true; fi
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover ./clover.xml

after_script:
  - if [ "$CODE_COVERAGE" = 1 ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$CODE_COVERAGE" = 1 ]; then php ocular.phar code-coverage:upload --format=php-clover ./clover.xml; fi

notifications:
  email: false
