language: php

sudo: required

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2

addons:
  hosts:
    - dovecot.travis.dev

env:
  global:
    - IMAP_SERVER_NAME=dovecot.travis.dev
    - IMAP_SERVER_PORT=993
    - IMAP_USERNAME=dovecot_travis_testuser
    - IMAP_PASSWORD=dovecot_travis_testpwd

cache:
  directories:
    - $HOME/.composer/cache

install:
  - sh .travis/dovecot_install.sh
  - phpenv config-rm xdebug.ini || true
  - composer install

script:
  - vendor/bin/phpunit

notifications:
  email: false
